### ISSUE TITLE
error An unexpected error occurred: "Command \"build\" not found."

### ISSUE THREAD

**Issue by simondate** [kaltura/kaltura-player-js#103]
Ran 
```
yarn run build
```

##### Expected behavior
A build to occour

##### Actual behavior
build failed.

##### Console output
```
$ yarn run build
yarn run v1.5.1
error An unexpected error occurred: "Command \"build\" not found.".
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\Users\\k1619153\\Desktop\\working\\kaltura-player-js\\yarn-error
.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
```

I noticed in package there is only `build:ovp` and `build:ott` but neither of these seemed to be working. I'm using node version `8.9.1`

**Comment by kaltura-hooks** [comment]
Hi @simondate,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Hi @simondate you are correct, indeed the docs are not updated to latest build targets.
Regarding `build:ovp`|`build:ott`- can you share the error you are receiving?

**Comment by simondate** [comment]
[yarn-error.log](https://github.com/kaltura/kaltura-player-js/files/1860020/yarn-error.log)

Hi @OrenMe , here's the error log

**Comment by OrenMe** [comment]
@simondate this is for build command, which we have split to `build:ovp` or `build:ott`.
You mentioned they don't work as well - I was referring to that issue.
Can you explain what you see when you run those commands?

**Comment by itaykinnrot** [comment]
@simondate let us know if the issue still exist - closing for now.

**Comment by simondate** [comment]
Sorry, I didn't get a chance to test this again. I built my application using just kWidget.
