### ISSUE TITLE
OTT vs OVP: What is the difference? Can we add it to the README?

### ISSUE THREAD

**Issue by stkrzysiak** [kaltura/kaltura-player-js#138]
I'd like to make a PR correcting the `yarn build` in the README to yard build:ott|ovp but in doing so I'd like to also add a note about which is which. Looking at our current platform I don't see any indicator if we are ott or ovp, and noting in our source code that would indicate either. How is this determined? The terms seem almost interchangeable.

**Comment by kaltura-hooks** [comment]
Hi @stkrzysiak,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
@stkrzysiak thanks for raising the issue. indeed from looking at the repo alone this might seem undermined as this is related to the actual setup of the Kaltura platform account.
If you are a Kaltura client I suggest you request your CSM/account manager to open the ability to use the player via the platform dashboard.

**Comment by stkrzysiak** [comment]
Thank you for the prompt response. We were told that our KMC ids were enabled for v3 of the player yet when looking at v3 of the platform studio editor there is nothing related to OVP/OTT. Nor do I see any direct relation between the editor(aside from configuring some behavior and associating it with a player id) and the actual player in this repository(which doesn't seem to need a player id). Is there something I should be specifically looking for? 
Also, The example app points at a QA api server, where do Kaltura clients testing out v0.30 find their API endpoint? 
I apologize if I'm asking too much here that I should be asking our CSM, I have an outstanding email on that avenue and really I'm just providing feedback as to what a typical developer may ask when they are told to research the implementation of v3 of this player.

**Comment by OrenMe** [comment]
Hi @stkrzysiak as I see you were answered in an email thread I'm closing this issue.
Feel free to ask additional question if needed.

**Comment by schwendinger** [comment]
^ answering this in the README instead of an internal email would be helpful for all kaltura customers.
