### ISSUE TITLE
PLAYER_DESTROY event is never fired when player is destroyed

### ISSUE THREAD

**Issue by icunioli** [kaltura/kaltura-player-js#160]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues)
- [ ] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: 0.33.1
- [x] Can you reproduce the issue with our latest release version
- [x] Can you reproduce the issue with the latest code from master
- [ ] What browser and OS names and versions are you using: Chrome 70.0.3538.67 / Firefox 62.0.3 on macOS 10.13.6
- [ ] If applicable, add test code or test page to reproduce: 
Please visit https://www.kaltura.com/index.php/extwidget/preview/partner_id/1836881/uiconf_id/42569642/entry_id/0_eqai5xf8/embed/dynamic, and then in the developer tools' console type the following
```javascript
kalturaPlayer.addEventListener(kalturaPlayer.Event.PLAYER_DESTROY, (e) => { debugger; })
kalturaPlayer.destroy()
```

##### Expected behavior
On `.destroy()`, the `PLAYER_DESTROY` event will fire and execute the callback

##### Actual behavior
No event is fired

**Comment by kaltura-hooks** [comment]
Hi @icunioli,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by icunioli** [comment]
> * Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
>   please provide as much details as possible.

Yes, it has been tested cross-browser and on different OSes

> * Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?

Kaltura SaaS

Thank you!

**Comment by OrenMe** [comment]
thanks for reporting @icunioli , indeed this is a bug - happens as the event is emitted on destroy after we clean the event manager queue.
This will be fixed on next version. I do not have a due date yet.

**Comment by icunioli** [comment]
Awesome @OrenMe! Is there any way I can help you with the fix?

On the other hand, how can we get updates when a new version is released? I've just noticed that the `PLAYBACK_STARTED` event has been renamed to `PLAYBACK_START` and that has caused us a lot of issues.

Thanks!

**Comment by dan-ziv** [comment]
@icunioli 
In addition to @OrenMe comment, please be aware that `PLAYBACK_START` event has different meaning from the legacy `PLAYBACK_STARTED` event, so if you replaced those enums in your app take the following into account:
* `PLAYBACK_STARTED` event enum changed to `FIRST_PLAYING` -  fired when the video element fires `playing` event for the first time (on each media).
* `PLAYBACK_START` - fired when the first play request occurs (whether for ads or playback).

**Comment by icunioli** [comment]
Thanks for the additional information @dan-ziv!

So, to check if I got it right:

- `FIRST_PLAYING` will fire when the playback starts (if there's a pre-roll ad, it would fire at that time. Otherwise, it would fire when the main entry starts playing).
- `PLAYBACK_START`will fire for each play request (if there's a pre-roll ad, it would fire twice: once for the pre-roll, and the other one for the main entry).

Is that correct?

Thanks!

**Comment by OrenMe** [comment]
Hi @icunioli - fix will be available in Nov 25th release
