### ISSUE TITLE
Player's SEEKING event being fired after user seeks

### ISSUE THREAD

**Issue by icunioli** [kaltura/kaltura-player-js#169]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues)
- [x] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: 0.33.1
- [x] Can you reproduce the issue with our latest release version
- [x] Can you reproduce the issue with the latest code from master
- [x] What browser and OS names and versions are you using: Chrome 70.0.3538.77 on macOS 10.10.5
- [x] If applicable, add test code or test page to reproduce:
Please visit https://www.kaltura.com/index.php/extwidget/preview/partner_id/1836881/uiconf_id/42569642/entry_id/0_eqai5xf8/embed/dynamic, and then in the developer tools' console type the following
```
kalturaPlayer.addEventListener(kalturaPlayer.Event.SEEKING, (e) => { console.log('SEEKING'); });
kalturaPlayer.addEventListener(kalturaPlayer.Event.SEEKED, (e) => { console.log('SEEKED'); });
```

##### Expected behavior
`kalturaPlayer.Event.SEEKING` fires at the right moment the user starts moving/skipping the video and not along with `kalturaPlayer.Event.SEEKED` event.

##### Actual behavior
`kalturaPlayer.Event.SEEKING` fires when the user finishes moving/skipping the video, along with `kalturaPlayer.Event.SEEKED` event.

**Comment by kaltura-hooks** [comment]
Hi @icunioli,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by icunioli** [comment]
> Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
please provide as much details as possible.

Yes, it is. Has been tested cross-browser and on different OSes too.

> Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?

Kaltura SaaS

Thanks!

**Comment by OrenMe** [comment]
Hi @icunioli, the seeking and seek events corresponds to the actual media element seek command.
When a user drags the scrubber it doesn't actually instigates a media seek request, and only when a user leaves the scrubber the actual media seek command is requested.
So seeking will be called and seek will be called afterwards whenever media seeking has finished.
The operation may be very quick for example on very fast networks or if seek is done to an already buffered region, so actual video data is already in the browser decoding pipe.
