### ISSUE TITLE
Add configurable playback rates

### ISSUE THREAD

**Issue by romanzipp** [kaltura/kaltura-player-js#238]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues): yes
- [x] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: 0.41.1
- [x] Can you reproduce the issue with our latest release version: yes
- [x] Can you reproduce the issue with the latest code from master: yes
- [x] What browser and OS names and versions are you using: 
- [x] If applicable, add test code or test page to reproduce: 

##### Expected
I'd love to see a `playbackRates` config option to support more rates than currently available.

```js
KalturaPlayer.setup({
    playback: {
        playbackRates: [0.25, 0.5, 1, 1.25, 1.5]
    }
});
```

##### Actual
The current playback rates are [hardcoded](https://github.com/kaltura/playkit-js/blob/aa67b09606fd75fd0dcd03b02f53784554773aee/src/engines/html5/html5.js#L170) to **0.5, 1, 2, 4**

**Comment by kaltura-hooks** [comment]
Hi @romanzipp,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Hi @romanzipp, thanks for writing.
We have this item in our roadmap and it should be available in Q3.
Please keep tuned to release notes once it is out.
