### ISSUE TITLE
Failed with Protocol Relative URLs

### ISSUE THREAD

**Issue by amohiy** [kaltura/kaltura-player-js#257]
hello,
i am trying to run kaltura player v3 on samsung smart TV but i notice that you are using Protocol Relative URLs example: ['//analytics.kaltura.com/api_v3/index.php']. In the browser it works fine but for the Smart TV, the TV always looking for it in the local files so some features does not work.
can you provide any help.

Thanks,
Ahmed

**Comment by kaltura-hooks** [comment]
Hi @amohiy,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amohiy** [comment]
i created a ovp player on KMC studio (TV platform studio) then i use the cdn link to embed it in my code  [ https://cdnapisec.kaltura.com/p/{partenerID}/embedPlaykitJs/uiconf_id/{uiconf_id} ] 
when i run the application on Samsung smart TV  "//analytics.kaltura.com/api_v3/index.php" this API does not work because it's a  Protocol Relative URLs and this feature does not work on Tv. 

Thanks

**Comment by OrenMe** [comment]
this will be resolved on next version due in two weeks.

**Comment by amohiy** [comment]
Thanks for your response, Will i find this issue as well if i use OTT player instead of OVP player.

**Comment by OrenMe** [comment]
@amohiy kava is embedded in the player and supplies insights to your QoE of your users.
I assume you are a platform user(you mentioned using the KMC) so you should be using OVP player which is offered through the studio.
A fix will be pushed to production on the 4th of Aug.

**Comment by amohiy** [comment]
Thanks so much.
