### ISSUE TITLE
kaltura player demo with ads code.

### ISSUE THREAD

**Issue by designerprasan007** [kaltura/kaltura-player-js#308]
##### Prerequisites
- [ ] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues): ______
- [ ] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: ______
- [ ] Can you reproduce the issue with our latest release version: ______
- [ ] Can you reproduce the issue with the latest code from master: ______
- [ ] What browser and OS names and versions are you using: ______
- [ ] If applicable, add test code or test page to reproduce: 
```
Paste test code here
``

##### Expected behavior
What you expected to happen

##### Actual behavior
What actually happened

##### Console output
```
Paste the contents of the browser console here.
```



hi, i'm a developer.  for one of my client i have to use kaltura player for ads purpose. so for this since morning i'm looking for the proper code but unfortunatly i'm not getting any of that. even i tried both of your github link
1  https://github.com/kaltura/kaltura-player-js and
2. https://github.com/kaltura.
none of this are working so kindly provide proper link of working thank you. waiting for replay.

**Comment by kaltura-hooks** [comment]
Hi @designerprasan007,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by designerprasan007** [comment]
hi thank you for your response,  i tried your given getting output of this in terminal.
-> root@ubuntu-s-2vcpu-4gb-sfo2-01:~# rpm -qa \"kaltura*\"
The program 'rpm' is currently not installed. You can install it by typing:
apt install rpm
root@ubuntu-s-2vcpu-4gb-sfo2-01:~# dpkg -l \"kaltura-*\"
dpkg-query: no packages found matching "kaltura-*"
root@ubuntu-s-2vcpu-4gb-sfo2-01:~# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
tail: cannot open '/opt/kaltura/log/*.log' for reading: No such file or directory
tail: cannot open '/opt/kaltura/log/batch/*.log' for reading: No such file or directory
tail: no files remaining. 
    i will try by installing the packages.

**Comment by OrenMe** [comment]
@designerprasan007 It sounds as you are having issues installing the CE of kaltura.
If you have a working environment please share a player test page.
