### ISSUE TITLE
Not showing webcam video on newrow smart room

### ISSUE THREAD

**Issue by bjorn3** [kaltura/kaltura-player-js#309]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues): None found
- [x] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: kaltura-player-js 0.39.2
- [ ] Can you reproduce the issue with our latest release version: N/A
- [ ] Can you reproduce the issue with the latest code from master: N/A
- [x] What browser and OS names and versions are you using: Firefox on Linux
- [x] If applicable, add test code or test page to reproduce: 
    https://smart.newrow.com/room

##### Expected behavior
Webcam video shown

##### Actual behavior
No webcam video shown. It keeps showing the loading spinner. Audio works fine.

##### Console output
```
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
```

and a lot of

```
Invalid URI. Load of media resource  failed.
```

**Comment by kaltura-hooks** [comment]
Hi @bjorn3,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by bjorn3** [comment]
> Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?

The issue is consistent. I don't have any other platforms to test it on.

> Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
If self hosted, are you using the RPM or deb install?

Newrow smart room, which is using kaltura internally.

> When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

![image](https://user-images.githubusercontent.com/17426603/77924731-55ecb280-72a4-11ea-9b9d-d4a56c1cd488.png)

**Comment by bjorn3** [comment]
It seems that the problem was a missing H.264 codec. A fallback to VP8 would be nice.

**Comment by OrenMe** [comment]
Hi @bjorn3, NewRow project is managed on another repo, please contact your CSM or account manager for support.
In general, codec support is platform dependent.
