### ISSUE TITLE
Chromcast does not work after playing it once and trying it on another video

### ISSUE THREAD

**Issue by ataherinmobly** [kaltura/kaltura-player-js#328]
##### Prerequisites
- [ ✓] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues): ______
- [ ] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: ______
- [✓ ] Can you reproduce the issue with our latest release version: ______
- [ ] Can you reproduce the issue with the latest code from master: ______
- [✓ ] What browser and OS names and versions are you using: Chrome
- [✓ ] If applicable, add test code or test page to reproduce: 
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Kaltura Test</h1>
    <div id="kaltura_player_969502727" style="width: 560px; height: 395px;"></div>


    <button onclick="runPlayer('0_1u2783i2')">Entry Test 1</button>
    <button onclick="runPlayer('0_pqrr5dc8')">Entry Test 2</button>
    <button onclick="runPlayer('0_4sk443pu')">Entry Test 3</button>
</body>
<script type="text/javascript" src="https://cdnapisec.kaltura.com/p/2454391/embedPlaykitJs/uiconf_id/43734881"></script>

<script>
    var kalturaPlayer;
    function runPlayer(entryIdParam) {
        try {
        if (kalturaPlayer && kalturaPlayer.destroy) {
            kalturaPlayer.destroy();
        }
         var entryId = entryIdParam;
         kalturaPlayer = KalturaPlayer.setup({
           targetId: "kaltura_player_969502727",
           provider: {
             partnerId: 2454391,
             uiConfId: 43734881,
           },
         });
         kalturaPlayer.loadMedia({ entryId: entryId });
         console.log(kalturaPlayer);
       } catch (e) {
         console.error(e.message);
       }
    }
</script>
</html>
```

##### Expected behavior
To be able to use Chromcast on a video when the chromcast is available. 
##### Actual behavior
When I play the video for the first time (example 1 or 2 or 3) The casting option is available and it casts. when I stop casting and switch to another video the casting option is no longer available unless I reload the page. We have andorid / IOS apps that works perfectly using kaltura sdks and casting.

##### Console output
```
```

**Comment by kaltura-hooks** [comment]
Hi @ataherinmobly,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by ataherinmobly** [comment]
![image](https://user-images.githubusercontent.com/48910813/85182763-f93cda80-b289-11ea-9ee7-3357eedfa755.png)

![image](https://user-images.githubusercontent.com/48910813/85182827-1e314d80-b28a-11ea-802c-d58b42af7a2f.png)

![image](https://user-images.githubusercontent.com/48910813/85182890-4e78ec00-b28a-11ea-88d2-f9f66cf914ea.png)


Here are some screenshots and here is a provided screen record for the issue: https://drive.google.com/file/d/1BCLYBadAYx3mfVcDFTWMa0Rl-NfRxD7F/view?usp=sharing


The issue is that when I play a video for the first time in the test website a casting option is available and when I cast the TV displays the video. When I stop casting and switch to another video the casting option is no longer available unless I reloaded the page. 

You can run the code given above using http-server or live server so that you would be able to cast.

**Comment by dan-ziv** [comment]
@ataherinmobly thanks for your feedback and for reporting this issue!
I know it took some time to get it done, but better late than never :-)

Related PRs:
kaltura/kaltura-player-js#417
kaltura/playkit-js-ui#582
kaltura/playkit-js-cast-sender#51
