### ISSUE TITLE
fragLoadError when switching to another network

### ISSUE THREAD

**Issue by sot-tech** [kaltura/kaltura-player-js#334]
##### Prerequisites
- [x] Have you checked for duplicate [issues](https://github.com/kaltura/kaltura-player-js/issues): ______
- [x] Which Plugin [version](https://github.com/kaltura/kaltura-player-js/releases) are you using: 0.51.3 (html5lib3-0.51.3-2, html5lib-2.82.2-1 from ubuntu repo)
- [ ] Can you reproduce the issue with our latest release version: n/a
- [ ] Can you reproduce the issue with the latest code from master: n/a
- [x] What browser and OS names and versions are you using: Chrome/83.0.4103.119 Linux-5.3, Chrome/83.0.4103.109 Android 9
- [x] If applicable, add test code or test page to reproduce: stock code without modifications

##### Expected behavior
When video is playing and device switching to another network and next video segment was not downloaded, player waits some time (2-3 sec.) and trying to reconnect to server.

##### Actual behavior
The player shows an error a moment after the network has become unavailable (with json error message), without any option to reconnect and continue playing.

##### Console output
See attachments. [vw.sottech.local-1594404703703.log](https://github.com/kaltura/kaltura-player-js/files/4904720/vw.sottech.local-1594404703703.log)

**Comment by kaltura-hooks** [comment]
Hi @sot-tech,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by sot-tech** [comment]
Hello.

> Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
please provide as much details as possible.

Same problem exist in windows 7+, linux 5.3 and android 7+ in chromium based browsers, in firefox player just stoppes playing (button 'play' becomes visible) and after pressing to 'play' button it stucks with console error:

```
Uncaught TypeError: this.playerObject is null
    jQuery 5
    dispatch https://vod.sottech.local/html5/html5lib/v2.82.2/mwEmbedFrame.php/p/101/uiconf_id/23448283?wid=_101&iframeembed=true&playerId=kaltura_player_1580937219&flashvars[playlistAPI.kpl0Id]=0_4bkp6ov4:175
    handle https://vod.sottech.local/html5/html5lib/v2.82.2/mwEmbedFrame.php/p/101/uiconf_id/23448283?wid=_101&iframeembed=true&playerId=kaltura_player_1580937219&flashvars[playlistAPI.kpl0Id]=0_4bkp6ov4:172
```

> Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?

Self-hosted all-in-one installation

> If self hosted, are you using the RPM or deb install?

deb-based install in ubuntu 16.04

> Packages installed.

see attachments [debs.txt](https://github.com/kaltura/kaltura-player-js/files/4904835/debs.txt)

> If running a self hosted ENV - provide the MySQL server version used

mysql  Ver 14.14 Distrib 5.6.48-88.0, for debian-linux-gnu (x86_64) using  6.3

> If running a self hosted ENV - is this a single all in 1 server or a cluster?

single all-in-one server

> If running a self hosted ENV, while making the problematic request, run:

see attachments [logs.txt](https://github.com/kaltura/kaltura-player-js/files/4904863/logs.txt)

> When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

see attachments [screen.zip](https://github.com/kaltura/kaltura-player-js/files/4904914/screen.zip)

**Comment by OrenMe** [comment]
hi @sot-tech, the issue you are raising is for v2 player and it seems like you are using the community edition.
Please use the community forums for such questions. Thanks.
