### ISSUE TITLE
Load by referenceId?

### ISSUE THREAD

**Issue by jbrule** [kaltura/kaltura-player-js#344]
I've looked through documentation on https://developer.kaltura.com/player/web/ and cannot find how to load by referenceId. We use this function a lot with the mwembed player. How is it down with playkit player?

Thank you,
Josh

**Comment by kaltura-hooks** [comment]
Hi @jbrule,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Hi @jbrule, thanks for raising this!
I will open an internal ticket for adding support.
If you have a CSM assigned please raise this with him/her to get notification when the feature is available.

**Comment by OrenMe** [comment]
Internal ticket ref: FEC-10387

**Comment by danielthedifficult** [comment]
Would love to see this as well. Currently, I have to do a first request to list media by referenceId, then load the entryId I get. It adds easily 2-3 seconds to page load.

**Comment by OrenMe** [comment]
the issue has been resolved in https://github.com/kaltura/kaltura-player-js/pull/369
