### ISSUE TITLE
InternalError: Too much recursion on IOS devices

### ISSUE THREAD

**Issue by visbits** [kaltura/kaltura-player-js#420]
Issue where player js crashes on IOS devices, can simulate on both IOS and Firefox Emulation of IOS device size.

Looks like the issue is related to 1.5.2 when a "bumper" (pre-played video) is enabled.  With that disabled, the issue does not present itself on IOS.

Uncaught (in promise) InternalError: too much recursion
    isFullscreen fullscreen-controller.js:73
    isFullscreen player.js:1377
    isFullscreen kaltura-player.js:391
    playOnMainVideoTag bumper.js:198
    get bumper-engine-decorator.js:23
    r engine-decorator.js:44
    get engine-decorator.js:44
    getVideoElement player.js:568

##### Prerequisites
CDN Delivered player version

##### Expected behavior

Bumper playback then HLS/DASH playback as seen on non IOS devices.

##### Actual behavior

engine-decorator.js crash.

##### Console output

```
Paste the contents of the browser console here.
```

**Comment by kaltura-hooks** [comment]
Hi @visbits,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
@visbits thanks for reporting, we are checking it.

**Comment by OrenMe** [comment]
Hi @visbits can you please share a test page where issue reproduces.

**Comment by dan-ziv** [comment]
@OrenMe 
https://github.com/kaltura/playkit-js-bumper/commit/381910e15c67560af7ba7e77b269963044b7ba00
Should solves this issue.
@visbits Can you verify it with latest bumper plugin version (v2.0.5)?
