### ISSUE TITLE
How to seek player to specific time when player is loaded

### ISSUE THREAD

**Issue by SalMinoz** [kaltura/kaltura-player-js#433]
Back when I used Kaltura Player v2, the player is able to `doSeek` to a specific time when a player is loaded. This function is just like the user watch time history. I want to implement this function in Kaltura Player v7. I have checked the document but couldn't find it yet. 

This is how I used it in Kaltura Player v2.
```
const kdp = document.getElementById(playerId);
kdp.sendNotification('doSeek', PLAYER_RECEIVE_EVENT.last_watched)
```

##### Expected behavior
When the player is loaded, The player should be loaded to a specific time duration. 

##### Actual behavior

I couldn't find a solution for Kaltura Player v7 yet. 

Really appreciate your support.

**Comment by kaltura-hooks** [comment]
Hi @SalMinoz,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,
