### ISSUE TITLE
Iframe embed: Cannot read property 'capabilities' of null

### ISSUE THREAD

**Issue by WolfOvs** [kaltura/kaltura-player-js#446]
Hello,

I'm trying to integrate a video on a Next.js project by iframe way, here the code I have in html:

`<iframe id="kaltura_player_1621337976" src="https://cdnapisec.kaltura.com/p/3444703/sp/344470300/embedIframeJs/uiconf_id/47937313/partner_id/3444703?iframeembed=true&playerId=kaltura_player_1621337976&entry_id=1_6tyuujvb" width="400" height="333" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" frameborder="0" itemprop="video" itemscope itemtype="http://schema.org/VideoObject">
        <span itemprop="name" content="Personal Capture Walkthrough "></span>
        <span itemprop="description" content="Learn how to use Kaltura's Personal Capture."></span>
        <span itemprop="duration" content="218"></span>
        <span itemprop="thumbnailUrl" content="https://cfvod.kaltura.com/p/3444703/sp/344470300/thumbnail/entry_id/1_6tyuujvb/version/100011"></span>
        <span itemprop="uploadDate" content="2021-05-14T06:16:10.000Z"></span>
        <span itemprop="width" content="400"></span>
        <span itemprop="height" content="333"></span>
        </iframe>`

I have the following error that i attach below:

<img width="668" alt="Schermata 2021-05-18 alle 13 30 21" src="https://user-images.githubusercontent.com/9006823/118643785-4a788580-b7dd-11eb-9e68-20f2072d2ec3.png">
<img width="757" alt="Schermata 2021-05-18 alle 13 30 05" src="https://user-images.githubusercontent.com/9006823/118643794-4cdadf80-b7dd-11eb-9bba-f34d9fbe5140.png">

Look like something about permissions, but on the platform I have everything configured as open:

<img width="771" alt="Schermata 2021-05-18 alle 13 32 04" src="https://user-images.githubusercontent.com/9006823/118643909-73991600-b7dd-11eb-86d3-ab8b78e6439e.png">

Any suggestions?

Thank you

**Comment by kaltura-hooks** [comment]
Hi @WolfOvs,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by WolfOvs** [comment]
Hello, thanks for the fast answer.

My environment is a front end project still running in localhost, builded with Next.js/React.
By the way also trying the preview on Kaltura platform I have the same error mentioned before:

<img width="436" alt="Schermata 2021-05-18 alle 13 53 39" src="https://user-images.githubusercontent.com/9006823/118646592-ac86ba00-b7e0-11eb-97fb-ce7a52b7c73a.png">

<img width="1163" alt="Schermata 2021-05-18 alle 13 53 57" src="https://user-images.githubusercontent.com/9006823/118646605-b14b6e00-b7e0-11eb-9f6e-2752ea9e6f48.png">

So I assume that the problem is inside Kaltura Saas.

My goal is integrate the iframe, I upload on Kaltura the content, Kaltura generate iframe and I integrate it on my website.

Is something that is provided by your service?

Thank you very much.

**Comment by yairans** [comment]
@WolfOvs Thank you for reporting the issue. 
You are using player v2 so need to open the issue for https://github.com/kaltura/mwEmbed.

**Comment by WolfOvs** [comment]
@yairans Ok I opened another here: https://github.com/kaltura/mwEmbed/issues/4225

Thank you
