### ISSUE TITLE
Failed to stream on LG Smart TV

### ISSUE THREAD

**Issue by amohiy** [kaltura/kaltura-player-js#458]
hello, 
we implemented  kaltura-player-js in our LG smart TV webapp, And every videos worked fine for sometimes but lately   we started to get this error and the video sometimes play and sometimes not here is the error:

[DashAdapter]  {severity: 2, category: 3, code: 3015, data: Array[1], handled: false}
DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

We use Drm in our solution
Testing Device:
LG Smart TV model 2017 FHD

we need to understand why we getting this error and how can we fix it fro
m our  side if it's possible. Bytheway when we run this app on chrome browser we don't get this error at all.

Thanks in advance.

<img width="1278" alt="Screen Shot 2021-06-16 at 12 21 54 PM" src="https://user-images.githubusercontent.com/28922554/122202668-8dda1880-ce9d-11eb-9636-c23ab0b4892b.png">

**Comment by kaltura-hooks** [comment]
Hi @amohiy,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by amohiy** [comment]
Any help thanks ?

**Comment by giladna** [comment]
Hi
There was issue with ad playback side by side
It should becok now with v3.4.0
